### ISSUE TITLE
Allow to import configuration from CSV

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/ModbusModules#37]
Allow to import configuration from csv, it should be able to use the files it exports

**Comment by wheelsailor** [comment]
Might need a bit of work... comparing configuration to export. 

![image](https://user-images.githubusercontent.com/6308119/53309609-baa14500-390d-11e9-96c9-b2c46478df2e.png)

**Comment by becega** [comment]
Yes it might be just be better to add similar function that some of the new modules with import export.  The export on this module was mostly to import it into Kepserver OPC.

**Comment by agomez08** [comment]
Fixed in #70
